# Generated by Django 5.0.2 on 2024-03-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFromSub', models.CharField(blank=True, default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Max Mustermann', max_length=100)),
                ('email', models.CharField(default='Max@Musteremail.at', max_length=100)),
                ('phonenumber', models.CharField(default='0123456', max_length=100)),
                ('short', models.CharField(default='MM', max_length=5)),
                ('iconColor', models.CharField(default='#FF7A00', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('category', models.CharField(default='No category', max_length=100)),
                ('color', models.CharField(default='0038FF', max_length=30)),
                ('description', models.CharField(default='No description', max_length=300)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority', models.CharField(default='low', max_length=30)),
                ('section', models.CharField(default='taskCategoryInProgress', max_length=50)),
                ('title', models.CharField(default='No title', max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('iconColor', models.ManyToManyField(related_name='task_icon_color', to='join_app_backend.contactmodel')),
                ('members', models.ManyToManyField(related_name='task_members', to='join_app_backend.contactmodel')),
                ('subtask', models.ManyToManyField(to='join_app_backend.subtaskmodel')),
            ],
        ),
    ]
