# Generated by Django 5.0.2 on 2024-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='members',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='assignedTo',
            field=models.ManyToManyField(related_name='task_assignedTo', to='join_app_backend.contactmodel'),
        ),
    ]
