# Generated by Django 5.0.2 on 2024-02-27 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empty title', max_length=100)),
                ('description', models.CharField(default='Empty description', max_length=500)),
                ('priority', models.CharField(default='to-do', max_length=100)),
                ('category', models.CharField(default='Max Mustermann', max_length=100)),
                ('subtask', models.CharField(default='nothing', max_length=500)),
                ('assigned_to', models.ManyToManyField(to='join_app_backend.contactmodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
