# Generated by Django 5.0.1 on 2024-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorFromIcon', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubtaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFromSub', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='iconColor',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='subtask',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='iconColor',
            field=models.ManyToManyField(to='join_app_backend.subtaskmodel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='subtask',
            field=models.ManyToManyField(to='join_app_backend.colormodel'),
        ),
    ]
