# Generated by Django 5.0.2 on 2024-03-07 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0002_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='assigned_to',
            new_name='members',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='color',
            field=models.CharField(default='0038FF', max_length=30),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='iconColor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='section',
            field=models.CharField(default='taskCategoryInProgress', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='category',
            field=models.CharField(default='No category', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(default='No description', max_length=300),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(default='low', max_length=30),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='subtask',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(default='No title', max_length=300),
        ),
    ]
