# Generated by Django 5.0.2 on 2024-03-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0002_remove_taskmodel_members_taskmodel_assignedto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='color',
            new_name='categoryColor',
        ),
    ]
