# Generated by Django 5.0.2 on 2024-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0003_rename_color_taskmodel_categorycolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='iconColor',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='assignedTo',
            field=models.ManyToManyField(to='join_app_backend.contactmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
