# Generated by Django 5.0.2 on 2024-03-07 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0003_rename_assigned_to_taskmodel_members_taskmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='iconColor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=[''], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='subtask',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=[''], null=True, size=None),
        ),
    ]
