# Generated by Django 5.0.2 on 2024-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0004_alter_taskmodel_iconcolor_alter_taskmodel_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='iconColor',
            field=models.JSONField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='subtask',
            field=models.JSONField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
    ]
