# Generated by Django 5.0.2 on 2024-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0005_alter_taskmodel_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskmodel',
            name='status',
            field=models.CharField(blank=True, default='unchecked', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='assignedTo',
            field=models.ManyToManyField(to='join_app_backend.contactmodel'),
        ),
    ]
