# Generated by Django 5.0.2 on 2024-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0007_taskmodel_date_alter_subtaskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date',
            field=models.DateField(default='31.12.2024', max_length=30),
        ),
    ]
