# Generated by Django 5.0.2 on 2024-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0008_alter_taskmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
