# Generated by Django 5.0.2 on 2024-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app_backend', '0009_alter_taskmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='subtask',
            field=models.ManyToManyField(blank=True, to='join_app_backend.subtaskmodel'),
        ),
    ]
